### PR TITLE
181 custom filter UI and interactions

### LINKED ISSUE #181: Discuss: Specification for Custom Filter UI and its interactions
### Custom Filter Menu
The top 3 options in filter menu are __single choice option__, which means can only choose one out of 3:
- **Reset Filter**
  - show all transactions (done and undone)
- **Filter by done or undone status**
  - click once show done transaction only
  - click again show undone transaction only
  - click another show done transaction again
- **Filter by positive or negative amount** 
  - click once show positive amt only
  - click again show negative amt only
  - click another show positive amt again

A divider divides between top 3 options and the rest of options.
The rest of the options are addictive, and is based on `filterTxn` command. When a user clicks on "Filter by Contact", the `filterTxn p/` will be written in command box UI. if there's command in command box, it will be overwritten.

>  Addictive means on top of say the "Filter by positive amount", I can filter by contact - Alex, which gets me all the positive amt transaction with Alex.

> Another example: Default app filter is show all transactions. Filter by contact - Alex, followed by filter by date - 01092024, gets me all transactions with Alex on 01/09/2024

- **Filter by Contact**
  - click once, `filterTxn p/` will be overwritten in command box.
- **Filter by Amount**
  - click once, `filterTxn amt/` will be overwritten in command box.
- **Filter by Description**
  - click once, `filterTxn desc/` will be overwritten in command box.
- **Filter by Date**
  - click once, `filterTxn date/` will be overwritten in command box.

---

### Intended behavior:
- When app starts:
  - Transaction list panel shows all transactions (done and undone).
  - Total balance overview panel track "You owe" and "You are owed" of all transactions.
  - Filter icon appears grayed.
- If a filter (not show all transaction) is applied:
  - Transaction list panel shows filtered transaction.
  - Total balance overview panel track the filtered transactions.
  - Filter icon is colored blue. Only when filter is reset, the filter icon back to grey.
- Regardless of filters applied, when app is restarted, the filter is back to default. i.e. filters are not saved to persistent storage upon closing of the app.
- Regardless of any address book commands or transaction commands, the existing filter remains and transaction list panel show filtered list.
  - Exceptions: `filterTxn` add/reset existing filter/s, `clearTxn` and `listTxn` reset filter to default (show all transactions).

### PR DESCRIPTION
**Pull request by GavinSin**
- [X]  This pull request is complete

### This PR aims to implement:
- Bugfix typo #207 
- Bugfix filter by +/- amt #231 
- Add filter by done/undone status for tracking done/undone transaction in total balance UI #215 
- Add custom filter menu UI according to spec #181 :
  - Make top 3 options _(Reset Filter, Filter by done/undone, Filter by +/- amt)_ be single choice options
  - Filter by Contact, Amount, Description, Date that set `filterTxn` text in command box.
  - Better filter icon that appear gray by default, and appear blue when a filter is applied.

---

### Acceptance Criteria
- When app starts:
  - Transaction list panel shows all transactions (done and undone).
  - Total balance overview panel track "You owe" and "You are owed" of all transactions.
  - Filter icon appears grayed.
- If a filter (not show all transaction) is applied:
  - Transaction list panel shows filtered transaction.
  - Total balance overview panel track the filtered transactions.
  - Filter icon is colored blue. Only when filter is reset, the filter icon back to grey.
- Regardless of filters applied, when app is restarted, the filter is back to default. i.e. filters are not saved to persistent storage upon closing of the app.
- Regardless of any address book commands or transaction commands, the existing filter remains and transaction list panel show filtered list.
  - Exceptions: `filterTxn` add/reset existing filter/s, `clearTxn` and `listTxn` reset filter to default (show all transactions).
- When the user:
  - **Reset Filter**
    - show all transactions (done and undone)
  - **Filter by done or undone status**
    - click once show done transaction only
    - click again show undone transaction only
    - click another show done transaction again
  - **Filter by positive or negative amount** 
    - click once show positive amt only
    - click again show negative amt only
    - click another show positive amt again
  - **Filter by Contact**
    - click once, `filterTxn p/` will be overwritten in command box.
  - **Filter by Amount**
    - click once, `filterTxn amt/` will be overwritten in command box.
  - **Filter by Description**
    - click once, `filterTxn desc/` will be overwritten in command box.
  - **Filter by Date**
    - click once, `filterTxn date/` will be overwritten in command box.

closes #181 #231 #215 #207

### CODE REVIEW

**Comment by GavinSin** [comment]
The custom filter menu UI is done, currently I looking for way to test `RightPanel` UI methods if possible. Else, can merge in liao.

**Comment by GavinSin** [comment]
I have added `RIghtPanelTest` under package `systemtests`, as part of Local GUI testing.

File: src/main/java/spleetwaise/transaction/ui/RightPanel.java [hunk 1]
```diff
@@ -81,38 +104,57 @@ private BigDecimal calculateBalance(ObservableList<Transaction> txns, Predicate<
...
+        filterByDone.setOnAction(e -> filterTransactionsByDoneStatus());
+
+        MenuItem filterByPositiveOrNegativeAmount = new MenuItem("Filter by Positive or Negative Amount");
+        filterByPositiveOrNegativeAmount.setOnAction(e -> filterTransactionsByAmount());
+
+        SeparatorMenuItem divider = new SeparatorMenuItem();
+
+        MenuItem filterByContact = new MenuItem("Filter by Contact");
+        filterByContact.setOnAction(
+                e -> commandBox.handleFilterCommandEntered(FilterCommand.COMMAND_WORD + " " + PREFIX_PHONE));
```
Comment (rollingpencil) [inline src/main/java/spleetwaise/transaction/ui/RightPanel.java:120]: Can change to no prefix since its index based now

File: src/main/java/spleetwaise/transaction/ui/RightPanel.java [hunk 2]
```diff
@@ -81,38 +104,57 @@ private BigDecimal calculateBalance(ObservableList<Transaction> txns, Predicate<
...
-        MenuItem filterByDateRange = new MenuItem("Filter by last month");
-        filterByDateRange.setOnAction(e -> filterTransactionsByLastMonth());
-
         MenuItem resetFilter = new MenuItem("Reset filter");
         resetFilter.setOnAction(e -> resetFilter());
 
-        filterMenu.getItems().addAll(resetFilter, filterByAmount, filterByDateRange);
-        filterMenu.show(filterIcon, event.getScreenX(), event.getScreenY());
+        MenuItem filterByDone = new MenuItem("Filter by Done or Not Done Status");
+        filterByDone.setOnAction(e -> filterTransactionsByDoneStatus());
```
Comment (rollingpencil) [inline src/main/java/spleetwaise/transaction/ui/RightPanel.java:111]: Can change to use some of the predicates

**Review by rollingpencil — APPROVED** [review]
LGTM. Just a few minor changes you can consider.
